#!/usr/bin/env bash

PROGNAME=$(basename $0)

opts=$@

nohup ./source/move_generator/bin/move_generator >>logs/coutput.log 2>&1 &
mgpid=$!
echo "MOVE GENERATOR PID: $mgpid"
echo -e "---------------------------\n" >> logs/coutput.log

pypy play.py --debug -p ab
echo -e "---------------------------\n" >> logs/pyoutput.log

echo "Making sure move_generator process has ended."
kill $mgpid
